version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - shared_network
    volumes:
      - .:/workspace
      - packages:/usr/local/lib/python3.9/site-packages
      - bin:/usr/local/bin

  db:
    image: postgres:10-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - shared_network
    environment:
      POSTGRES_DB: fast_tmi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.0.1-alpine
    ports:
      - 6379:6379
    networks:
      - redis-network

networks:
  shared_network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  db-volume: null
  packages: null
  bin: null
